package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1



/**
 * Carritopro generated by hbm2java
 */
public class Carritopro  implements java.io.Serializable {


     private int idcart;
     private Articulospro articulospro;
     private Clientespro clientespro;
     private String foto1;
     private Integer cantidad;
     private String add1;
     private String add2;
     private String add3;
     private String add4;

    public Carritopro() {
    }

	
    public Carritopro(int idcart) {
        this.idcart = idcart;
    }
    public Carritopro(int idcart, Articulospro articulospro, Clientespro clientespro, String foto1, Integer cantidad, String add1, String add2, String add3, String add4) {
       this.idcart = idcart;
       this.articulospro = articulospro;
       this.clientespro = clientespro;
       this.foto1 = foto1;
       this.cantidad = cantidad;
       this.add1 = add1;
       this.add2 = add2;
       this.add3 = add3;
       this.add4 = add4;
    }
   
    public int getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(int idcart) {
        this.idcart = idcart;
    }
    public Articulospro getArticulospro() {
        return this.articulospro;
    }
    
    public void setArticulospro(Articulospro articulospro) {
        this.articulospro = articulospro;
    }
    public Clientespro getClientespro() {
        return this.clientespro;
    }
    
    public void setClientespro(Clientespro clientespro) {
        this.clientespro = clientespro;
    }
    public String getFoto1() {
        return this.foto1;
    }
    
    public void setFoto1(String foto1) {
        this.foto1 = foto1;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getAdd1() {
        return this.add1;
    }
    
    public void setAdd1(String add1) {
        this.add1 = add1;
    }
    public String getAdd2() {
        return this.add2;
    }
    
    public void setAdd2(String add2) {
        this.add2 = add2;
    }
    public String getAdd3() {
        return this.add3;
    }
    
    public void setAdd3(String add3) {
        this.add3 = add3;
    }
    public String getAdd4() {
        return this.add4;
    }
    
    public void setAdd4(String add4) {
        this.add4 = add4;
    }




}


