package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriapro generated by hbm2java
 */
public class Categoriapro  implements java.io.Serializable {


     private int idcategoria;
     private String nombre;
     private Set articulospros = new HashSet(0);

    public Categoriapro() {
    }

	
    public Categoriapro(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public Categoriapro(int idcategoria, String nombre, Set articulospros) {
       this.idcategoria = idcategoria;
       this.nombre = nombre;
       this.articulospros = articulospros;
    }
   
    public int getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getArticulospros() {
        return this.articulospros;
    }
    
    public void setArticulospros(Set articulospros) {
        this.articulospros = articulospros;
    }




}


