package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientespro generated by hbm2java
 */
public class Clientespro  implements java.io.Serializable {


     private int idcliente;
     private String nombre;
     private String dni;
     private String direccion;
     private String telefono;
     private String correo;
     private String password;
     private String admin;
     private Set comprapros = new HashSet(0);
     private Set wishlistpros = new HashSet(0);
     private Set carritopros = new HashSet(0);
     private Set reviewpros = new HashSet(0);

    public Clientespro() {
    }

	
    public Clientespro(int idcliente) {
        this.idcliente = idcliente;
    }
    public Clientespro(int idcliente, String nombre, String dni, String direccion, String telefono, String correo, String password, String admin, Set comprapros, Set wishlistpros, Set carritopros, Set reviewpros) {
       this.idcliente = idcliente;
       this.nombre = nombre;
       this.dni = dni;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.password = password;
       this.admin = admin;
       this.comprapros = comprapros;
       this.wishlistpros = wishlistpros;
       this.carritopros = carritopros;
       this.reviewpros = reviewpros;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }
    public Set getComprapros() {
        return this.comprapros;
    }
    
    public void setComprapros(Set comprapros) {
        this.comprapros = comprapros;
    }
    public Set getWishlistpros() {
        return this.wishlistpros;
    }
    
    public void setWishlistpros(Set wishlistpros) {
        this.wishlistpros = wishlistpros;
    }
    public Set getCarritopros() {
        return this.carritopros;
    }
    
    public void setCarritopros(Set carritopros) {
        this.carritopros = carritopros;
    }
    public Set getReviewpros() {
        return this.reviewpros;
    }
    
    public void setReviewpros(Set reviewpros) {
        this.reviewpros = reviewpros;
    }




}


