package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprapro generated by hbm2java
 */
public class Comprapro  implements java.io.Serializable {


     private int idcompra;
     private Clientespro clientespro;
     private Date fechacompra;
     private Integer preciototal;
     private String text;
     private String modopago;
     private String fechaenvio;
     private Set pedidospros = new HashSet(0);

    public Comprapro() {
    }

	
    public Comprapro(int idcompra) {
        this.idcompra = idcompra;
    }
    public Comprapro(int idcompra, Clientespro clientespro, Date fechacompra, Integer preciototal, String text, String modopago, String fechaenvio, Set pedidospros) {
       this.idcompra = idcompra;
       this.clientespro = clientespro;
       this.fechacompra = fechacompra;
       this.preciototal = preciototal;
       this.text = text;
       this.modopago = modopago;
       this.fechaenvio = fechaenvio;
       this.pedidospros = pedidospros;
    }
   
    public int getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(int idcompra) {
        this.idcompra = idcompra;
    }
    public Clientespro getClientespro() {
        return this.clientespro;
    }
    
    public void setClientespro(Clientespro clientespro) {
        this.clientespro = clientespro;
    }
    public Date getFechacompra() {
        return this.fechacompra;
    }
    
    public void setFechacompra(Date fechacompra) {
        this.fechacompra = fechacompra;
    }
    public Integer getPreciototal() {
        return this.preciototal;
    }
    
    public void setPreciototal(Integer preciototal) {
        this.preciototal = preciototal;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getModopago() {
        return this.modopago;
    }
    
    public void setModopago(String modopago) {
        this.modopago = modopago;
    }
    public String getFechaenvio() {
        return this.fechaenvio;
    }
    
    public void setFechaenvio(String fechaenvio) {
        this.fechaenvio = fechaenvio;
    }
    public Set getPedidospros() {
        return this.pedidospros;
    }
    
    public void setPedidospros(Set pedidospros) {
        this.pedidospros = pedidospros;
    }




}


