package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1



/**
 * ParamproId generated by hbm2java
 */
public class ParamproId  implements java.io.Serializable {


     private int idarticulo;
     private String paramName;

    public ParamproId() {
    }

    public ParamproId(int idarticulo, String paramName) {
       this.idarticulo = idarticulo;
       this.paramName = paramName;
    }
   
    public int getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }
    public String getParamName() {
        return this.paramName;
    }
    
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParamproId) ) return false;
		 ParamproId castOther = ( ParamproId ) other; 
         
		 return (this.getIdarticulo()==castOther.getIdarticulo())
 && ( (this.getParamName()==castOther.getParamName()) || ( this.getParamName()!=null && castOther.getParamName()!=null && this.getParamName().equals(castOther.getParamName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdarticulo();
         result = 37 * result + ( getParamName() == null ? 0 : this.getParamName().hashCode() );
         return result;
   }   


}


