package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1



/**
 * Parampro generated by hbm2java
 */
public class Parampro  implements java.io.Serializable {


     private ParamproId id;
     private Articulospro articulospro;
     private String paramType;
     private String param1;
     private String param2;
     private String param3;
     private String param4;
     private String param5;
     private String param6;
     private String param7;
     private String param8;
     private String param9;

    public Parampro() {
    }

	
    public Parampro(ParamproId id, Articulospro articulospro) {
        this.id = id;
        this.articulospro = articulospro;
    }
    public Parampro(ParamproId id, Articulospro articulospro, String paramType, String param1, String param2, String param3, String param4, String param5, String param6, String param7, String param8, String param9) {
       this.id = id;
       this.articulospro = articulospro;
       this.paramType = paramType;
       this.param1 = param1;
       this.param2 = param2;
       this.param3 = param3;
       this.param4 = param4;
       this.param5 = param5;
       this.param6 = param6;
       this.param7 = param7;
       this.param8 = param8;
       this.param9 = param9;
    }
   
    public ParamproId getId() {
        return this.id;
    }
    
    public void setId(ParamproId id) {
        this.id = id;
    }
    public Articulospro getArticulospro() {
        return this.articulospro;
    }
    
    public void setArticulospro(Articulospro articulospro) {
        this.articulospro = articulospro;
    }
    public String getParamType() {
        return this.paramType;
    }
    
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }
    public String getParam1() {
        return this.param1;
    }
    
    public void setParam1(String param1) {
        this.param1 = param1;
    }
    public String getParam2() {
        return this.param2;
    }
    
    public void setParam2(String param2) {
        this.param2 = param2;
    }
    public String getParam3() {
        return this.param3;
    }
    
    public void setParam3(String param3) {
        this.param3 = param3;
    }
    public String getParam4() {
        return this.param4;
    }
    
    public void setParam4(String param4) {
        this.param4 = param4;
    }
    public String getParam5() {
        return this.param5;
    }
    
    public void setParam5(String param5) {
        this.param5 = param5;
    }
    public String getParam6() {
        return this.param6;
    }
    
    public void setParam6(String param6) {
        this.param6 = param6;
    }
    public String getParam7() {
        return this.param7;
    }
    
    public void setParam7(String param7) {
        this.param7 = param7;
    }
    public String getParam8() {
        return this.param8;
    }
    
    public void setParam8(String param8) {
        this.param8 = param8;
    }
    public String getParam9() {
        return this.param9;
    }
    
    public void setParam9(String param9) {
        this.param9 = param9;
    }




}


