package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1



/**
 * PedidosproId generated by hbm2java
 */
public class PedidosproId  implements java.io.Serializable {


     private int idcompra;
     private int idarticulo;
     private String add1;
     private String add2;
     private String add3;
     private String add4;

    public PedidosproId() {
    }

    public PedidosproId(int idcompra, int idarticulo, String add1, String add2, String add3, String add4) {
       this.idcompra = idcompra;
       this.idarticulo = idarticulo;
       this.add1 = add1;
       this.add2 = add2;
       this.add3 = add3;
       this.add4 = add4;
    }
   
    public int getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(int idcompra) {
        this.idcompra = idcompra;
    }
    public int getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }
    public String getAdd1() {
        return this.add1;
    }
    
    public void setAdd1(String add1) {
        this.add1 = add1;
    }
    public String getAdd2() {
        return this.add2;
    }
    
    public void setAdd2(String add2) {
        this.add2 = add2;
    }
    public String getAdd3() {
        return this.add3;
    }
    
    public void setAdd3(String add3) {
        this.add3 = add3;
    }
    public String getAdd4() {
        return this.add4;
    }
    
    public void setAdd4(String add4) {
        this.add4 = add4;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidosproId) ) return false;
		 PedidosproId castOther = ( PedidosproId ) other; 
         
		 return (this.getIdcompra()==castOther.getIdcompra())
 && (this.getIdarticulo()==castOther.getIdarticulo())
 && ( (this.getAdd1()==castOther.getAdd1()) || ( this.getAdd1()!=null && castOther.getAdd1()!=null && this.getAdd1().equals(castOther.getAdd1()) ) )
 && ( (this.getAdd2()==castOther.getAdd2()) || ( this.getAdd2()!=null && castOther.getAdd2()!=null && this.getAdd2().equals(castOther.getAdd2()) ) )
 && ( (this.getAdd3()==castOther.getAdd3()) || ( this.getAdd3()!=null && castOther.getAdd3()!=null && this.getAdd3().equals(castOther.getAdd3()) ) )
 && ( (this.getAdd4()==castOther.getAdd4()) || ( this.getAdd4()!=null && castOther.getAdd4()!=null && this.getAdd4().equals(castOther.getAdd4()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcompra();
         result = 37 * result + this.getIdarticulo();
         result = 37 * result + ( getAdd1() == null ? 0 : this.getAdd1().hashCode() );
         result = 37 * result + ( getAdd2() == null ? 0 : this.getAdd2().hashCode() );
         result = 37 * result + ( getAdd3() == null ? 0 : this.getAdd3().hashCode() );
         result = 37 * result + ( getAdd4() == null ? 0 : this.getAdd4().hashCode() );
         return result;
   }   


}


