package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1



/**
 * Pedidospro generated by hbm2java
 */
public class Pedidospro  implements java.io.Serializable {


     private PedidosproId id;
     private Articulospro articulospro;
     private Comprapro comprapro;
     private Integer cantidad;

    public Pedidospro() {
    }

	
    public Pedidospro(PedidosproId id, Articulospro articulospro, Comprapro comprapro) {
        this.id = id;
        this.articulospro = articulospro;
        this.comprapro = comprapro;
    }
    public Pedidospro(PedidosproId id, Articulospro articulospro, Comprapro comprapro, Integer cantidad) {
       this.id = id;
       this.articulospro = articulospro;
       this.comprapro = comprapro;
       this.cantidad = cantidad;
    }
   
    public PedidosproId getId() {
        return this.id;
    }
    
    public void setId(PedidosproId id) {
        this.id = id;
    }
    public Articulospro getArticulospro() {
        return this.articulospro;
    }
    
    public void setArticulospro(Articulospro articulospro) {
        this.articulospro = articulospro;
    }
    public Comprapro getComprapro() {
        return this.comprapro;
    }
    
    public void setComprapro(Comprapro comprapro) {
        this.comprapro = comprapro;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


