package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1



/**
 * ReviewproId generated by hbm2java
 */
public class ReviewproId  implements java.io.Serializable {


     private int idarticulo;
     private int idcliente;

    public ReviewproId() {
    }

    public ReviewproId(int idarticulo, int idcliente) {
       this.idarticulo = idarticulo;
       this.idcliente = idcliente;
    }
   
    public int getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReviewproId) ) return false;
		 ReviewproId castOther = ( ReviewproId ) other; 
         
		 return (this.getIdarticulo()==castOther.getIdarticulo())
 && (this.getIdcliente()==castOther.getIdcliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdarticulo();
         result = 37 * result + this.getIdcliente();
         return result;
   }   


}


