package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reviewpro generated by hbm2java
 */
public class Reviewpro  implements java.io.Serializable {


     private ReviewproId id;
     private Articulospro articulospro;
     private Clientespro clientespro;
     private Integer stars;
     private String text;
     private Date fecha;

    public Reviewpro() {
    }

	
    public Reviewpro(ReviewproId id, Articulospro articulospro, Clientespro clientespro) {
        this.id = id;
        this.articulospro = articulospro;
        this.clientespro = clientespro;
    }
    public Reviewpro(ReviewproId id, Articulospro articulospro, Clientespro clientespro, Integer stars, String text, Date fecha) {
       this.id = id;
       this.articulospro = articulospro;
       this.clientespro = clientespro;
       this.stars = stars;
       this.text = text;
       this.fecha = fecha;
    }
   
    public ReviewproId getId() {
        return this.id;
    }
    
    public void setId(ReviewproId id) {
        this.id = id;
    }
    public Articulospro getArticulospro() {
        return this.articulospro;
    }
    
    public void setArticulospro(Articulospro articulospro) {
        this.articulospro = articulospro;
    }
    public Clientespro getClientespro() {
        return this.clientespro;
    }
    
    public void setClientespro(Clientespro clientespro) {
        this.clientespro = clientespro;
    }
    public Integer getStars() {
        return this.stars;
    }
    
    public void setStars(Integer stars) {
        this.stars = stars;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


