package pojos;
// Generated 06-ene-2020 20:16:15 by Hibernate Tools 4.3.1



/**
 * Wishlistpro generated by hbm2java
 */
public class Wishlistpro  implements java.io.Serializable {


     private WishlistproId id;
     private Articulospro articulospro;
     private Clientespro clientespro;
     private Integer quantity;

    public Wishlistpro() {
    }

	
    public Wishlistpro(WishlistproId id, Articulospro articulospro, Clientespro clientespro) {
        this.id = id;
        this.articulospro = articulospro;
        this.clientespro = clientespro;
    }
    public Wishlistpro(WishlistproId id, Articulospro articulospro, Clientespro clientespro, Integer quantity) {
       this.id = id;
       this.articulospro = articulospro;
       this.clientespro = clientespro;
       this.quantity = quantity;
    }
   
    public WishlistproId getId() {
        return this.id;
    }
    
    public void setId(WishlistproId id) {
        this.id = id;
    }
    public Articulospro getArticulospro() {
        return this.articulospro;
    }
    
    public void setArticulospro(Articulospro articulospro) {
        this.articulospro = articulospro;
    }
    public Clientespro getClientespro() {
        return this.clientespro;
    }
    
    public void setClientespro(Clientespro clientespro) {
        this.clientespro = clientespro;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


